# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-31 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[(('dv', 'development'), 'development'), (('ps', 'personal'), 'personal')], default=('dv', 'development'), max_length=2),
        ),
    ]
