# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-31 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20170831_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('dv', 'development'), ('ps', 'personal')], default='dv', max_length=2),
        ),
    ]
